/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserGroupEditor.java
 *
 * Created on 2009-8-18, 13:52:29
 */
package prj.ui.user;

import com.hongxin.component.ComponentUtil;
import com.hongxin.util.service.ServiceUtils;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import java.util.List;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultListModel;
import org.jdesktop.application.Application;
import prj.user.po.Role;
import prj.user.po.UserGroup;

/**
 * 当前在线用户的权限查询
 * @author dangzerong
 */
public class CurrentUserRight extends javax.swing.JDialog
{
	/**
	 * 资源文件对象
	 */
	private ResourceMap rm;
	/**
	 * 用户组对象
	 */
	private UserGroup userGroupInfo;
	/**
	 * 角色集合。
	 */
	private List<Role> listRole;
	/**
	 * 角色列表。
	 */
	private Set<Integer> listSysRoleId;
	/**
	 * 用户组名称集合。
	 */
	private Set<String> listGroupName;
	/**
	 * 设备列表。
	 */
	private Set<Integer> listDeviceId;
	/**
	 * 设备组列表。
	 */
	private Set<Integer> listDeviceGroupId;
	/**
	 * mml命令列表。
	 */
	private Set<Integer> listMmlId;
	/**
	 * 根子网列表。
	 */
	private Set<Integer> listDistrictId;
	
	/**
	 * 初始化用户组编辑界面
	 * @param parent 顶层窗口对象
	 * @param modal 窗口模式 true:模式窗口；false:非模式窗口
	 * @param groupData 用户组对象
	 */
	public CurrentUserRight(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		rm = Application.getInstance().getContext().getResourceMap(CurrentUserRight.class);
		userGroupInfo = new UserGroup();
		listRole = new ArrayList();
		listSysRoleId = new HashSet();
		listGroupName = new HashSet();
		listDeviceId = new HashSet();
		listDeviceGroupId = new HashSet();
		listMmlId = new HashSet();
		listDistrictId = new HashSet();
		initComponents();
		
		// 执行初始化任务
		getAllUserInfo();
//		Task acquireTask = new AcquireUserDataTask();
//		Application.getInstance().getContext().getTaskService().execute(acquireTask);
	}

	private void getAllUserInfo()
	{
		listGroupName.addAll(new ArrayList());
		listRole.addAll(new ArrayList());
		listSysRoleId.addAll(new ArrayList());
	}
	
	/**
	 * 初始化界面。
	 */
	private void initialize()
	{
		StringBuilder sbd = new StringBuilder();
		// 遍历用户组
		for(String name : listGroupName)
		{
			// 多个用户组名称
			if(sbd.length() > 0)
			{
				sbd.append("&nbsp;/&nbsp;");
			}
			sbd.append(rm.getString("msg.group.name", name));
		}
		// 用户组名称列表
		tfName.setText(rm.getString("msg.group.list", sbd.toString()));
		// 设备组权限
		userGroupInfo.getListGroupId().addAll(listDeviceGroupId);
		// 设备权限
		userGroupInfo.getDevices().addAll(listDeviceId);
		// 系统权限
		userGroupInfo.getListRoleId().addAll(listSysRoleId);
		// mml命令权限
		userGroupInfo.getMMLCommands().addAll(listMmlId);
		// 根子网权限
		userGroupInfo.getDistricts().addAll(listDistrictId);

		// 初始化角色
		initSysRole();

	}
	
	
	/**
	 * 初始化角色。
	 */
	private boolean initSysRole()
	{
		sysRoleFuncTree.initModel();
		// 显示角色名称和明细
		if(listRole != null && !listRole.isEmpty() && !listSysRoleId.isEmpty())
		{
			// 显示角色名称
			StringBuilder sbd = new StringBuilder();
			for(Role role : listRole)
			{
				if(listSysRoleId.contains(role.getId()))
				{
					if(sbd.length() > 0)
					{
						sbd.append(",");
					}
					sbd.append(role.getName());
				}
			}
			mainTabbedPane.setTitleAt(mainTabbedPane.indexOfComponent(sysRolePanel), 
					rm.getString("msg.role.title", sbd.toString()));
			// 依次获取角色权限
			for(Integer roleId : listSysRoleId)
			{
//				OmcProcessor.process(Command.user, Command.getSysRole,
//						roleId, new ProcessCallback()
//				{
//					@Override
//					public void processCompleted(final ProcessData out)
//					{
//						javax.swing.SwingUtilities.invokeLater(new Runnable()
//						{
//							@Override
//							public void run()
//							{
//								if(out.getData() != null)
//								{
//									sysRoleFuncTree.addSelectedFunction((List)out.getData());
//								}
//							}
//						});
//					}
//				});
				sysRoleFuncTree.addSelectedFunction(new ArrayList());
			}
		}
		return true;
	}

	/**
	 * 获得权限表列名
	 * @return  权限表列名
	 */
	private List getPurTableColumns()
	{
		List columns = new ArrayList();
		columns.add(rm.getString("jSystemPurview.column.title1"));
		columns.add(rm.getString("jSystemPurview.column.title2"));
		return columns;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblName = new javax.swing.JLabel();
        tfName = new javax.swing.JLabel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        sysRolePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sysRoleFuncTree = new com.hongxin.omc.ui.user.SysRoleFuncTree();
        mmlPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mmlPurview = ComponentUtil.createTreeTable(true, false);
        devicePanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableDeviceGroup = GUIUtil.createTable();
        jLabel3 = new javax.swing.JLabel();
        jDevNum = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        devicePurview = ComponentUtil.createTable(true, false);
        rootDistrictPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listRootDistrict = new com.jidesoft.swing.CheckBoxList();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(CurrentUserRight.class);
        setTitle(resourceMap.getString("Dialog_CurrentUserRight.title")); // NOI18N
        setName("Dialog_CurrentUserRight"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                CurrentUserRight.this.windowClosed(evt);
            }
        });

        lblName.setText(resourceMap.getString("lblName.text")); // NOI18N
        lblName.setMaximumSize(new java.awt.Dimension(120, 15));
        lblName.setMinimumSize(new java.awt.Dimension(38, 15));
        lblName.setName("lblName"); // NOI18N

        tfName.setText(resourceMap.getString("tfName.text")); // NOI18N
        tfName.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("tfName.border.lineColor"))); // NOI18N
        tfName.setName("tfName"); // NOI18N

        mainTabbedPane.setName("mainTabbedPane"); // NOI18N

        sysRolePanel.setName("sysRolePanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sysRoleFuncTree.setCheckBoxEnabled(false);
        sysRoleFuncTree.setName("sysRoleFuncTree"); // NOI18N
        sysRoleFuncTree.setRootVisible(false);
        jScrollPane1.setViewportView(sysRoleFuncTree);

        javax.swing.GroupLayout sysRolePanelLayout = new javax.swing.GroupLayout(sysRolePanel);
        sysRolePanel.setLayout(sysRolePanelLayout);
        sysRolePanelLayout.setHorizontalGroup(
            sysRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysRolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        sysRolePanelLayout.setVerticalGroup(
            sysRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysRolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab(resourceMap.getString("sysRolePanel.TabConstraints.tabTitle"), sysRolePanel); // NOI18N

        mmlPanel.setName("mmlPanel"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        mmlPurview.setName("mmlPurview"); // NOI18N
        jScrollPane2.setViewportView(mmlPurview);

        javax.swing.GroupLayout mmlPanelLayout = new javax.swing.GroupLayout(mmlPanel);
        mmlPanel.setLayout(mmlPanelLayout);
        mmlPanelLayout.setHorizontalGroup(
            mmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mmlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        mmlPanelLayout.setVerticalGroup(
            mmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mmlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab(resourceMap.getString("mmlPanel.TabConstraints.tabTitle"), mmlPanel); // NOI18N

        devicePanel.setName("devicePanel"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        tableDeviceGroup.setModel(new DeviceGroupTableModel());
        tableDeviceGroup.setName("tableDeviceGroup"); // NOI18N
        jScrollPane4.setViewportView(tableDeviceGroup);
        // 渲染器
        tableDeviceGroup.getColumnModel().getColumn(2).setCellRenderer(new DeviceFilterRenderer());
        // 不允许编辑
        ((DeviceGroupTableModel)tableDeviceGroup.getModel()).setEditable(false);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jDevNum.setText(resourceMap.getString("jDevNum.text")); // NOI18N
        jDevNum.setName("jDevNum"); // NOI18N
        jDevNum.setPreferredSize(new java.awt.Dimension(60, 15));

        jScrollPane3.setName("jScrollPane3"); // NOI18N
        jScrollPane3.setPreferredSize(new java.awt.Dimension(400, 240));

        devicePurview.setAutoCreateRowSorter(true);
        devicePurview.setModel(new DevModel());
        devicePurview.setName("devicePurview"); // NOI18N
        jScrollPane3.setViewportView(devicePurview);

        javax.swing.GroupLayout devicePanelLayout = new javax.swing.GroupLayout(devicePanel);
        devicePanel.setLayout(devicePanelLayout);
        devicePanelLayout.setHorizontalGroup(
            devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, devicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, devicePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDevNum, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        devicePanelLayout.setVerticalGroup(
            devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDevNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab(resourceMap.getString("devicePanel.TabConstraints.tabTitle"), devicePanel); // NOI18N

        rootDistrictPanel.setName("rootDistrictPanel"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        listRootDistrict.setModel(new DefaultListModel());
        listRootDistrict.setCheckBoxEnabled(false);
        listRootDistrict.setName("listRootDistrict"); // NOI18N
        jScrollPane5.setViewportView(listRootDistrict);

        javax.swing.GroupLayout rootDistrictPanelLayout = new javax.swing.GroupLayout(rootDistrictPanel);
        rootDistrictPanel.setLayout(rootDistrictPanelLayout);
        rootDistrictPanelLayout.setHorizontalGroup(
            rootDistrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootDistrictPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        rootDistrictPanelLayout.setVerticalGroup(
            rootDistrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootDistrictPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab(resourceMap.getString("rootDistrictPanel.TabConstraints.tabTitle"), rootDistrictPanel); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(CurrentUserRight.class, this);
        btnExit.setAction(actionMap.get("exit")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainTabbedPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap())
        );

        mainTabbedPane.getAccessibleContext().setAccessibleName(resourceMap.getString("mainTabbedPane.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_windowClosed
    {//GEN-HEADEREND:event_windowClosed
        exit();
    }//GEN-LAST:event_windowClosed

	/**
	 * 退出
	 */
	@Action
	public void exit()
	{
		dispose();
		if(listRole != null)
		{
			listRole.clear();
		}
		if(listSysRoleId != null)
		{
			listSysRoleId.clear();
		}
		if(listGroupName != null)
		{
			listGroupName.clear();
		}
		if(listDeviceId != null)
		{
			listDeviceId.clear();
		}
		if(listDeviceGroupId != null)
		{
			listDeviceGroupId.clear();
		}
		if(listMmlId != null)
		{
			listMmlId.clear();
		}
		if(listDistrictId != null)
		{
			listDistrictId.clear();
		}
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel devicePanel;
    private javax.swing.JTable devicePurview;
    private DefaultTableModel devModel;
    private javax.swing.JLabel jDevNum;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblName;
    private com.jidesoft.swing.CheckBoxList listRootDistrict;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel mmlPanel;
    private org.jdesktop.swingx.JXTreeTable mmlPurview;
    private javax.swing.JPanel rootDistrictPanel;
    private com.hongxin.omc.ui.user.SysRoleFuncTree sysRoleFuncTree;
    private javax.swing.JPanel sysRolePanel;
    private javax.swing.JTable tableDeviceGroup;
    private javax.swing.JLabel tfName;
    // End of variables declaration//GEN-END:variables

}

