/*
 * Copyright 2009 Hongxin Telecommunication Technologies Co, Ltd.,
 * Wuhan, Hubei, China. All rights reserved.
 */

/*
 * LockSession.java
 *
 * Created on 2010-2-23, 13:50:21
 */
package prj.ui.user;

import com.hongxin.component.ComponentUtil;
import com.hongxin.component.PainterUtil;
import com.hongxin.saf.SingleFrameApplication;
import com.hongxin.util.GUIUtils;
import java.awt.Frame;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import javax.swing.JOptionPane;
import org.jdesktop.application.Application;
import org.jdesktop.swingx.painter.AlphaPainter;

/**
 * 身份验证面板。
 * @author dangzerong
 */
public class IdentityValidate extends javax.swing.JDialog
{
	/**
	 * 是否取消。
	 */
	private boolean cancelClicked = true;
	/**
	 * 资源文件对象
	 */
	private ResourceMap resourceMap;

	/** Creates new form LockSession */
	public IdentityValidate(Frame owner, boolean modal)
	{
		super(owner, modal);
		resourceMap =
				Application.getInstance().getContext().getResourceMap(IdentityValidate.class);
		initComponents();
		// background painter
		AlphaPainter painter = new AlphaPainter();
		painter.setAlpha(0.75f);
		painter.setPainters(PainterUtil.defaultPinstripePainter());
		mainPanel.setBackgroundPainter(painter);
	}

	/**
	 * 显示界面。
	 * @return 是否取消
	 */
	public static boolean showDialog()
	{
		IdentityValidate dialog = new IdentityValidate(SingleFrameApplication.getInstance().getMainFrame(), true);
		GUIUtils.centerOnScreen(dialog);
		GUIUtils.addHideAction(dialog);
		dialog.getRootPane().setDefaultButton(dialog.btnConfirm);
		SingleFrameApplication.getInstance().show(dialog);
		return !dialog.cancelClicked;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new org.jdesktop.swingx.JXPanel();
        lblUser = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnConfirm = ComponentUtil.createPaintableButton();
        btnCancel = ComponentUtil.createPaintableButton();
        tfPassword = new javax.swing.JPasswordField();
        textAnimation = new com.hongxin.component.animation.LogoTextAnimation();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(IdentityValidate.class);
        setTitle(resourceMap.getString("Dialog_IdentityValidate_1.title")); // NOI18N
        setName("Dialog_IdentityValidate_1"); // NOI18N
        setResizable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        mainPanel.setName("mainPanel"); // NOI18N

        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText(resourceMap.getString("lblUser.text")); // NOI18N
        lblUser.setName("lblUser"); // NOI18N

        tfUser.setName("tfUser"); // NOI18N

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText(resourceMap.getString("lblPassword.text")); // NOI18N
        lblPassword.setName("lblPassword"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(IdentityValidate.class, this);
        btnConfirm.setAction(actionMap.get("confirm")); // NOI18N
        btnConfirm.setName("btnConfirm"); // NOI18N

        btnCancel.setAction(actionMap.get("exit")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N

        tfPassword.setText(resourceMap.getString("tfPassword.text")); // NOI18N
        tfPassword.setName("tfPassword"); // NOI18N

        textAnimation.setName("textAnimation"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(textAnimation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnConfirm))
                .addContainerGap())
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
	{//GEN-HEADEREND:event_formWindowClosing
		exit();
	}//GEN-LAST:event_formWindowClosing

	@Action
	public void confirm()
	{
		String user = tfUser.getText();
		String password = new String(tfPassword.getPassword());
		// 用户名不区分大小写
		if((user.equalsIgnoreCase(UserSession.getInstance().getUserInfo().getName())
				|| user.equalsIgnoreCase(UserSession.getInstance().getUserInfo().getAlias()))
				&& password.equals(UserSession.getInstance().getUserInfo().getPassword()))
		{
			dispose();
			cancelClicked = false;
		}
		else
		{
			JOptionPane.showMessageDialog(this,
					resourceMap.getString("mb.error"),
					resourceMap.getString("msg.err"),
					JOptionPane.INFORMATION_MESSAGE);
		}
	}

	/**
	 * 退出
	 */
	@Action
	public void exit()
	{
		dispose();
		cancelClicked = true;
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUser;
    private org.jdesktop.swingx.JXPanel mainPanel;
    private com.hongxin.component.animation.LogoTextAnimation textAnimation;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
