/*
 * Copyright 2010 Hongxin Telecommunication Technologies Co, Ltd.,
 * Wuhan, Hubei, China. All rights reserved.
 */

/*
 * OnlineUserPanel.java
 *
 * Created on 2012-5-10, 9:26:02
 */
package prj.ui.user;

import com.hongxin.saf.SingleFrameApplication;
import com.hongxin.util.GUIUtils;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.table.AbstractTableModel;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 * 在线用户面板。
 * @author fanhuigang
 */
public class OnlineUserPanel extends javax.swing.JPanel
{
	/**
	 * 用于显示的dialog。
	 */
	private JDialog dialog;
	private ResourceMap resourceMap;
	
	/** Creates new form OnlineUserPanel */
	public OnlineUserPanel()
	{
		resourceMap = Application.getInstance().getContext().getResourceMap(OnlineUserPanel.class);
		initComponents();
		initialize();
	}
	
	/**
	 * 显示界面。
	 */
	public static void showDialog()
	{
		final OnlineUserPanel oup = new OnlineUserPanel();
		oup.dialog = new JDialog(SingleFrameApplication.getInstance().getMainFrame(), true);
		oup.dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		oup.dialog.setName(oup.getName());
		oup.dialog.add(oup);
		oup.dialog.setTitle(oup.resourceMap.getString("form.title"));
		GUIUtils.addHideAction(oup.dialog);
		oup.dialog.getRootPane().setDefaultButton(oup.btnClose);
		oup.dialog.addWindowListener(new java.awt.event.WindowAdapter()
		{
			@Override
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				oup.close();
			}
		});
		oup.dialog.pack();
		SingleFrameApplication.getInstance().show(oup.dialog);
	}
	
	/**
	 * 初始化操作。
	 */
	private void initialize()
	{
		// 查询在线用户列表
		updateOnlineUser();
	}
	
	/**
	 * 更新在线用户列表。
	 */
	private void updateOnlineUser()
	{
		// 查询在线用户列表
		OmcProcessor.process(Command.data, Command.queryUsersOnline, 
				null, new ProcessCallback()
		{
			@Override
			public void processCompleted(final ProcessData out)
			{
				if(out.getData() != null)
				{
					com.hongxin.util.HxSwingUtilities.invokeLater(new Runnable()
					{
						@Override
						public void run()
						{
							// 更新表格模型
							((OnlineUserTableModel)tableUser.getModel()).initModel((OnlineUser[])out.getData());
						}
					});
				}
			}			
		});
	}
	
	/**
	 * 在线用户表格模型。
	 */
	private class OnlineUserTableModel extends AbstractTableModel
	{
		/**
		 * 模型数据源。
		 */
		private OnlineUser[] datasource;
		/**
		 * 表格列。
		 */
		private List<String> columns;
		
		/**
		 * 
		 * 增加了列序号   
		*/
		public OnlineUserTableModel()
		{
			columns = new ArrayList<String>();
			columns.add(resourceMap.getString("table.cols.index"));
			columns.add(resourceMap.getString("table.cols.name"));
			columns.add(resourceMap.getString("table.cols.address"));
			columns.add(resourceMap.getString("table.cols.time"));
			columns.add(resourceMap.getString("table.cols.type"));
			columns.add(resourceMap.getString("table.cols.idle"));
		}
		
		/**
		 * 初始化模型数据。
		 * @param datasource 模型数据
		 */
		public void initModel(OnlineUser[] datasource)
		{
			this.datasource = datasource;
			this.fireTableDataChanged();
		}
		
		@Override
		public int getRowCount()
		{
			return datasource == null ? 0 : datasource.length;
		}

		@Override
		public int getColumnCount()
		{
			return columns.size();
		}
		
		@Override
		public String getColumnName(int column)
		{
			return columns.get(column);
		}

		@Override
		public Object getValueAt(int row, int col)
		{
			OnlineUser user = datasource[row];
			switch(col)
			{
				case 0:
					return row + 1;
				case 1:
					return user.getName();
				case 2:
					return user.getNetAddress();
				case 3:
					return user.getLoginTime();
				case 4:
					return user.getLoginType();
				case 5:
					return user.getIdleTime();
			}
			return null;
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userScrollPane = new javax.swing.JScrollPane();
        tableUser = GUIUtil.createTable();
        btnClose = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setName("Form_OnlineUserPanel"); // NOI18N

        userScrollPane.setName("userScrollPane"); // NOI18N

        tableUser.setModel(new OnlineUserTableModel());
        tableUser.setName("tableUser"); // NOI18N
        userScrollPane.setViewportView(tableUser);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(OnlineUserPanel.class, this);
        btnClose.setAction(actionMap.get("close")); // NOI18N
        btnClose.setName("btnClose"); // NOI18N

        btnUpdate.setAction(actionMap.get("update")); // NOI18N
        btnUpdate.setName("btnUpdate"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnUpdate))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * 关闭窗口
	 */
	@Action
	public void close()
	{
		if(dialog != null)
		{
			dialog.dispose();
		}
	}

	@Action
	public void update()
	{
		// 更新在线用户列表
		updateOnlineUser();
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable tableUser;
    private javax.swing.JScrollPane userScrollPane;
    // End of variables declaration//GEN-END:variables
}
