/*
 * Copyright 2013 Hongxin Telecommunication Technologies Co, Ltd.,
 * Wuhan, Hubei, China. All rights reserved.
 */

/*
 * UserGroupSwitch.java
 *
 * Created on 2015-10-27, 10:54:15
 */

package com.hongxin.omc.ui.user;

import com.hongxin.component.renderer.ConverterRenderer;
import com.hongxin.omc.operation.Command;
import com.hongxin.omc.operation.OmcProcessor;
import com.hongxin.omc.operation.UserSession;
import com.hongxin.omc.ui.user.converter.UserGroupTypeConverter;
import com.hongxin.omc.user.protocol.UserGroup;
import com.hongxin.omc.util.OmcConstants;
import com.hongxin.speed.core.ProcessCallback;
import com.hongxin.speed.core.ProcessData;
import com.hongxin.util.GUIUtils;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 * 切换用户组类型对话框
 * @author xiangyu
 */
public class UserGroupSwitch extends javax.swing.JDialog
{
	/**
	 * 资源文件对象
	 */
	private ResourceMap rm;
	/**
	 * 用户组对象
	 */
	private UserGroup userGroupInfo;
	/**
	 * 用户信息处理状态
	 */
	public boolean isok = false;

    /** Creates new form UserGroupSwitch */
    public UserGroupSwitch(java.awt.Frame parent, boolean modal, UserGroup userGroup)
	{
        super(parent, modal);
		rm = Application.getInstance().getContext().getResourceMap(UserGroupSwitch.class);
		userGroupInfo = userGroup;
		isok = false;
        initComponents();
		// 初始化操作
		initialize();
    }
	
	/**
	 * 初始化用户信息
	 */
	private void initialize()
	{
		GUIUtils.addHideAction(UserGroupSwitch.this);
		getRootPane().setDefaultButton(btnOk);
		// 初始化下拉列表
		for(Integer groupType : UserGroupTypeConverter.instance.getListSValue())
		{
			// 根据当前操作用户的最高类型控制列表项
			int topType = UserSession.getInstance().getUserInfo().getTopGroupType();
			if(groupType <= topType)
			{
				cmbGroupType.addItem(groupType);
			}
		}
		this.setTitle(rm.getString("title"));
		if(userGroupInfo.getGroupType() == UserGroup.TYPE_PREP)
		{
			cmbGroupType.setSelectedItem(UserGroup.TYPE_PREP);
		}
		else if(userGroupInfo.getGroupType() > UserGroup.TYPE_SUPER)
		{
			// 顶级用户组显示为超级用户组
			cmbGroupType.setSelectedItem(UserGroup.TYPE_SUPER);
		}
		else
		{
			cmbGroupType.setSelectedItem(userGroupInfo.getGroupType());
		}
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblGroupType = new javax.swing.JLabel();
        cmbGroupType = new javax.swing.JComboBox();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(UserGroupSwitch.class);
        lblGroupType.setText(resourceMap.getString("lblGroupType.text")); // NOI18N
        lblGroupType.setName("lblGroupType"); // NOI18N

        cmbGroupType.setName("cmbGroupType"); // NOI18N
        cmbGroupType.setRenderer(new ConverterRenderer(UserGroupTypeConverter.instance));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(UserGroupSwitch.class, this);
        btnOk.setAction(actionMap.get("saveUserGroup")); // NOI18N
        btnOk.setName("btnOk"); // NOI18N

        btnCancel.setAction(actionMap.get("exit")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGroupType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGroupType, 0, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGroupType)
                    .addComponent(cmbGroupType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * 保存
	 */
	@Action
	public void saveUserGroup()
	{
		// 用户组名称
		int userGroupId = this.userGroupInfo.getId();
		final int userGroupTypeId = (Integer)cmbGroupType.getSelectedItem();
		if(userGroupTypeId == this.userGroupInfo.getGroupType())
		{
			JOptionPane.showMessageDialog(null,
					rm.getString("mb.usergroup.notchanged"),
					rm.getString("msg.prompt"),
					JOptionPane.INFORMATION_MESSAGE);
			return;
		}
		int obj[] = new int[2];
		obj[0] = userGroupId;
		obj[1] = userGroupTypeId;
		final CyclicBarrier barrier = new CyclicBarrier(2);
		try
		{
			barrier.reset();
			OmcProcessor.process(Command.user, Command.switchUserGroup,
					obj, new ProcessCallback()
			{
				@Override
				public void processCompleted(final ProcessData out)
				{
					try
					{
						barrier.await();
					}
					catch(Exception exp)
					{}
					javax.swing.SwingUtilities.invokeLater(new Runnable()
					{
						@Override
						public void run()
						{
							// 0 失败
							// 1 成功
							switch(out.getState())
							{
								//失败
								case 0:
									JOptionPane.showMessageDialog(null,
											rm.
											getString("mb.switchusergroup.fail"),
											rm.getString("msg.prompt"),
											JOptionPane.INFORMATION_MESSAGE);
									break;
								//成功
								case 1:
									JOptionPane.showMessageDialog(null,
											rm.
											getString("mb.switchusergroup.success"),
											rm.getString("msg.prompt"),
											JOptionPane.INFORMATION_MESSAGE);
									//刷新用户组列表
									isok = true;
									userGroupInfo.setGroupType(userGroupTypeId);
									UserGroupSwitch.this.dispose();
									break;
							}
						}
					});
				}
			});
			barrier.await(OmcConstants.sync_timeout2, TimeUnit.MILLISECONDS);
		}
		catch(Exception exp)
		{
			JOptionPane.showMessageDialog(null,
					rm.getString("msg.timeout"),
					rm.getString("msg.prompt"),
					JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * 退出
	 */
	@Action
	public void exit()
	{
		dispose();
		isok = false;
	}	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cmbGroupType;
    private javax.swing.JLabel lblGroupType;
    // End of variables declaration//GEN-END:variables

}
